PREFIX schema: <https://schema.org/> 
PREFIX bio: <https://bioschemas.org/> # tmp
PREFIX wikibase: <http://wikiba.se/ontology#>

CONSTRUCT {
?supersecondary_structure wdt:P31 wd:Q7644128.
?supersecondary_structure wdt:P361 ?part_of.
}
  
WHERE {
{?supersecondary_structure wdt:P31/wdt:P279* wd:Q7644128}
UNION {?supersecondary_structure wdt:P31/wdt:P279* wd:Q215980. ?supersecondary_structure wdt:P361 ?part_of.}

SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" }
}