PREFIX schema: <https://schema.org/> 
PREFIX bio: <https://bioschemas.org/> # tmp
PREFIX wikibase: <http://wikiba.se/ontology#>

CONSTRUCT {
?taxon wdt:P31 wd:Q16521.
}

WHERE {
{?taxon wdt:P31/wdt:P279* wd:Q16521.} # timesout

SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" }
}
